name: documentation-generator

on:
  pull_request:

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-docs:
    name: terraform-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Render terraform docs and commit back
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: .
          config-file: .terraform-docs.yml
          output-file: README.md
          output-method: inject
          git-push: true
          git-commit-message: "docs: terraform-docs auto-update [skip ci]"
